### ISSUE TITLE
wasm example does not work on Node.js

### ISSUE THREAD

**Issue by aidalgol** [refilelabs/image#6]
Trying to run the example in [`wasm/README.md`](https://github.com/refilelabs/image/blob/e68aa0afcb046a98de2f4cf432106a91e3a75d6c/wasm/README.md) (modified to read a file from disk) fails, with an uncaught exception from `__wbg_init`.
```console
❯ node image-example.mjs
node:internal/deps/undici/undici:13392
Error.captureStackTrace(err);
^

TypeError: fetch failed
at node:internal/deps/undici/undici:13392:13
at async __wbg_init (file:///path/to/project/assets/node_modules/@refilelabs/image/image.js:371:51)
at async file:///path/to/project/assets/image-example.mjs:4:1 {
[cause]: Error: not implemented... yet...
at makeNetworkError (node:internal/deps/undici/undici:9166:35)
at schemeFetch (node:internal/deps/undici/undici:10561:34)
at node:internal/deps/undici/undici:10410:26
at mainFetch (node:internal/deps/undici/undici:10429:11)
at fetching (node:internal/deps/undici/undici:10377:7)
at fetch (node:internal/deps/undici/undici:10246:20)
at fetch (node:internal/deps/undici/undici:13390:10)
at fetch (node:internal/bootstrap/web/exposed-window-or-worker:72:12)
at __wbg_init (file:///path/to/project/assets/node_modules/@refilelabs/image/image.js:366:26)
at file:///path/to/project/assets/image-example.mjs:4:7
}

Node.js v22.11.0
```

<details>
<summary>image-example.mjs</summary>

```js
import fs from "node:fs"
import init, { loadMetadata, getPixels, convertImage } from "@refilelabs/image"

await init()

const file = fs.readFileSync("sample.webp")
const srcType = "image/webp"
const targetType = "image/avif"

const metadata = loadMetadata(file, srcType, (progress) =>
  console.log(`Progress: ${progress}%`),
)
console.log("Metadata:", metadata)

const imageData = getPixels(file, srcType)
console.log("Image Data:", imageData)

const converted = convertImage(file, srcType, targetType, (progress) =>
  console.log(`Progress: ${progress}%`),
)
console.log("Converted Image:", converted)
fs.writeFileSync("output.avif", converted)
```
</details>

<details>
<summary>package.json</summary>

```json
{
  "dependencies": {
    "@refilelabs/image": "^0.1.0"
  }
}
```
</details>

**Comment by tomvoet** [comment]
Sorry I only tested this with Bun, I'll check if I can find a fix for Node. Thanks for letting me know :)

**Comment by tomvoet** [comment]
Hi again! I've narrowed it down to this "issue" with nodejs/undici#3741.
For node.js you can use:
```js
const wasmBuffer = fs.readFileSync('node_modules/@refilelabs/image/image_bg.wasm')

await init(wasmBuffer)
```
instead of:

```js
await init()
```

Let me know if this helps you :)

**Comment by aidalgol** [comment]
Yep, that works.  Thanks!

**Comment by tomvoet** [comment]
I've added this to the readme, which will also be included on npm within the next release :)

**Comment by Trojanking123** [comment]
hi, i met the same problem when i use id at chrome extension. it's not a nodejs.
i use WXT to develop my extension.

![Image](https://github.com/user-attachments/assets/a730627a-151c-4855-bde4-83811ddbfac6)

**Comment by Trojanking123** [comment]
> hi, i met the same problem when i use id at chrome extension. it's not a nodejs. i use WXT to develop my extension.
> 
> ![Image](https://github.com/user-attachments/assets/a730627a-151c-4855-bde4-83811ddbfac6)

Here is my code:
```js
    browser.runtime.onInstalled.addListener(async () => {
        try {
            await init();
            browser.contextMenus.create({
                id: "downloadImage",
                title: "下载图片",
                contexts: ["image"],
            }, () => {
                if (browser.runtime.lastError) {
                    console.error('创建菜单失败:', browser.runtime.lastError);
                } else {
                    console.log('右键菜单创建成功');
                }
            });
        } catch (error) {
            console.error('创建菜单出错:', error);
        }
    });
```

**Comment by tomvoet** [comment]
Hi @Trojanking123 I'm not a huge extension expert, I'll try my best tho :)
Can you provide a little reproduction so I can investigate myself?
